### ISSUE TITLE
unable to capture lineage in workspace

### ISSUE THREAD

**Issue by HBsunflower** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#215]
Exception while executing function: Functions.OpenLineageIn Result: Failure
Exception: System.Collections.Generic.KeyNotFoundException: The given key 'run' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at System.Collections.ObjectModel.ReadOnlyDictionary`2.get_Item(TKey key)
   at Function.Domain.Middleware.ScopedLoggingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\Purview-ADB-Lineage-Solution-Accelerator\Purview-ADB-Lineage-Solution-Accelerator\function-app\adb-to-purview\src\Function.Domain\Middleware\ScopedLogging.cs:line 38
   at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 166
Stack:    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at System.Collections.ObjectModel.ReadOnlyDictionary`2.get_Item(TKey key)
   at Function.Domain.Middleware.ScopedLoggingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\Purview-ADB-Lineage-Solution-Accelerator\Purview-ADB-Lineage-Solution-Accelerator\function-app\adb-to-purview\src\Function.Domain\Middleware\ScopedLogging.cs:line 38
   at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 166

**Comment by wjohnson** [comment]
@HBsunflower I know this issue is ancient at this point but do you have any additional details?

This should only occur if the OpenLineage payload is malformed as it will always include the `run` key.
